name: ibex-murphy-scan

on:
  schedule:
    - cron: '*/30 7-15 * * 1-5'   # cada 30 min en horario de mercado
  workflow_dispatch:

permissions:
  contents: write  # 🔑 necesario para poder hacer commits automáticos

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure positions_state.csv exists
        run: |
          if [ ! -f positions_state.csv ]; then
            echo "ticker,last_action,timestamp" > positions_state.csv
            echo "[Init] positions_state.csv creado vacío."
          fi

      - name: Show files (debug)
        run: |
          echo "Files in repo:"
          ls -R
          echo "Head of run.py:"
          head -n 20 run.py

      - name: Syntax check
        run: |
          python -m py_compile notifier.py run.py data.py config.py strategy_manager.py strategy_performance.py || true
          python -m py_compile strategies/*.py || true

      - name: Run scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
          TIMEZONE: "Europe/Madrid"
        run: |
          python run.py

      # 🔄 Guardar el estado actualizado de posiciones
      - name: Commit and push position state
        if: success()
        run: |
          git config --global user.email "murphy-bot@github.com"
          git config --global user.name "Murphy Bot"
          git add positions_state.csv
          git diff --staged --quiet || git commit -m "🤖 Update positions_state.csv [skip ci]"
          git push


