name: ibex-murphy-scan

on:
  schedule:
    # Ejecutar cada 2 horas dentro de la ventana 09:30 - 21:30 CET (Madrid)
    - cron: '30 9,11,13,15,17,19,21 * * 1-5'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache positions_state.csv
        uses: actions/cache@v4
        with:
          path: positions_state.csv
          key: positions-${{ github.run_id }}
          restore-keys: |
            positions-

      - name: Run scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
          TIMEZONE: "Europe/Madrid"
        run: |
          python run.py


