name: ibex-murphy-scan

on:
  schedule:
    - cron: '*/30 7-15 * * 1-5'   # cada 30 min en horario de mercado (ajusta si quieres)
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # puedes usar 3.10 o 3.12 si lo prefieres

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show files (debug)
        run: |
          echo "Files in repo:"
          ls -R
          echo "Head of run.py:"
          head -n 40 run.py

      - name: Syntax check
        run: |
          python -m py_compile notifier.py run.py data.py config.py strategy_manager.py strategy_performance.py || true
          python -m py_compile strategies/*.py || true

      - name: Run scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
          TIMEZONE: "Europe/Madrid"
        run: |
          python run.py


